export default [
    {
        key: 1,
        imgSrc: '/logo192.png',
        imgAlt: 'logo',
        children: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam accumsan consectetur libero, sit amet interdum neque mattis sed. Aenean faucibus erat ac ante sollicitudin interdum. Curabitur ultricies felis sagittis mi posuere eleifend. Etiam tincidunt cursus odio non pharetra. Sed ut porttitor ante. Nullam varius ipsum sit amet tortor maximus, quis egestas nisl pellentesque. Duis quis aliquet tortor, ut pharetra neque. Sed mi neque, convallis nec mi ut, congue cursus ex. Nunc mi erat, vestibulum eget lorem eu, scelerisque blandit arcu. Proin non neque et erat aliquet viverra sed ut mauris. Sed sed blandit velit. Cras porttitor eget lectus in luctus. Mauris id massa enim. Morbi finibus lobortis massa et blandit. Sed eu est leo. Phasellus volutpat sem in finibus ultricies. Fusce convallis eros vitae ante molestie dapibus. Proin non tristique nisl. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum varius sodales tellus id scelerisque. Duis pulvinar, ex quis pharetra volutpat, lorem nisl sollicitudin libero, quis condimentum nibh libero quis lorem. Ut sit amet nisi mauris. Vestibulum vel metus hendrerit, vestibulum nulla vitae, suscipit nunc. Phasellus magna elit, volutpat a urna sit amet, tincidunt congue augue. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque a placerat velit. Nulla condimentum ante sodales mi pellentesque ornare. Donec quam felis, commodo a velit non, tincidunt efficitur magna. Sed convallis nunc non sagittis laoreet. Nulla porttitor sem vel enim porta suscipit.',
        author: 'TodoresteG'
    },
    {
        key: 2,
        imgSrc: '/logo192.png',
        imgAlt: 'logo',
        children: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam accumsan consectetur libero, sit amet interdum neque mattis sed. Aenean faucibus erat ac ante sollicitudin interdum. Curabitur ultricies felis sagittis mi posuere eleifend. Etiam tincidunt cursus odio non pharetra. Sed ut porttitor ante. Nullam varius ipsum sit amet tortor maximus, quis egestas nisl pellentesque. Duis quis aliquet tortor, ut pharetra neque. Sed mi neque, convallis nec mi ut, congue cursus ex. Nunc mi erat, vestibulum eget lorem eu, scelerisque blandit arcu. Proin non neque et erat aliquet viverra sed ut mauris. Sed sed blandit velit. Cras porttitor eget lectus in luctus. Mauris id massa enim. Morbi finibus lobortis massa et blandit. Sed eu est leo. Phasellus volutpat sem in finibus ultricies. Fusce convallis eros vitae ante molestie dapibus. Proin non tristique nisl. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum varius sodales tellus id scelerisque. Duis pulvinar, ex quis pharetra volutpat, lorem nisl sollicitudin libero, quis condimentum nibh libero quis lorem. Ut sit amet nisi mauris. Vestibulum vel metus hendrerit, vestibulum nulla vitae, suscipit nunc. Phasellus magna elit, volutpat a urna sit amet, tincidunt congue augue. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque a placerat velit. Nulla condimentum ante sodales mi pellentesque ornare. Donec quam felis, commodo a velit non, tincidunt efficitur magna. Sed convallis nunc non sagittis laoreet. Nulla porttitor sem vel enim porta suscipit.',
        author: 'Anonymous'
    },
    {
        key: 3,
        imgSrc: '/logo192.png',
        imgAlt: 'logo',
        children: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam accumsan consectetur libero, sit amet interdum neque mattis sed. Aenean faucibus erat ac ante sollicitudin interdum. Curabitur ultricies felis sagittis mi posuere eleifend. Etiam tincidunt cursus odio non pharetra. Sed ut porttitor ante. Nullam varius ipsum sit amet tortor maximus, quis egestas nisl pellentesque. Duis quis aliquet tortor, ut pharetra neque. Sed mi neque, convallis nec mi ut, congue cursus ex. Nunc mi erat, vestibulum eget lorem eu, scelerisque blandit arcu. Proin non neque et erat aliquet viverra sed ut mauris. Sed sed blandit velit. Cras porttitor eget lectus in luctus. Mauris id massa enim. Morbi finibus lobortis massa et blandit. Sed eu est leo. Phasellus volutpat sem in finibus ultricies. Fusce convallis eros vitae ante molestie dapibus. Proin non tristique nisl. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum varius sodales tellus id scelerisque. Duis pulvinar, ex quis pharetra volutpat, lorem nisl sollicitudin libero, quis condimentum nibh libero quis lorem. Ut sit amet nisi mauris. Vestibulum vel metus hendrerit, vestibulum nulla vitae, suscipit nunc. Phasellus magna elit, volutpat a urna sit amet, tincidunt congue augue. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque a placerat velit. Nulla condimentum ante sodales mi pellentesque ornare. Donec quam felis, commodo a velit non, tincidunt efficitur magna. Sed convallis nunc non sagittis laoreet. Nulla porttitor sem vel enim porta suscipit.',
        author: 'Ivan'
    }
];